# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5eee1fa32cac4e7410b3624aa364434fcb27a1552dcce59fb0182c73d5ab7b598003f3f107205c25e53aadd9ec599cb8a03d1df6b4c35873adc2cc305724153f

test:
  secret_key_base: e6ffd21ef06b39cfdf5d533a401b0bd54a8f97d4456d63bb034141539279d225f20da82b9b611e18deef0854e6232378373ecab5d0a481f8d539b831d3d68937

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
